// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiPrac4.Data;

#nullable disable

namespace WebApiPrac4.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261002170739_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.31");

            modelBuilder.Entity("WebApiPrac4.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Almaty",
                            Description = "Команда из Алматы.",
                            Name = "Almaty Falcons"
                        },
                        new
                        {
                            Id = 2,
                            City = "Astana",
                            Description = "Команда из Астаны.",
                            Name = "Astana Nomads"
                        },
                        new
                        {
                            Id = 3,
                            City = "Shymkent",
                            Description = "Команда из Шымкента.",
                            Name = "Shymkent Tigers"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
